public class TrailblazerCertification {
    public String title;
    public String description;
    public String dateCompleted;    // Before asking why... This date is sent as a String by Trailhead API
    public String dateExpired;      // Before asking why... This date is sent as a String by Trailhead API
    public String certificationUrl;
    public String certificationStatus;
    public String certificationImageUrl;
}
